# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "contract"
out = "build"
test = "test"
script = "script"
libs = [
  "dependencies"
]
# https://github.com/ethereum/solidity/releases
solidity_version = '0.8.28'
# https://docs.blockscout.com/setup/information-and-settings/evm-version-information
evm_version = 'shanghai'

[dependencies]
forge-std = { version = "1.9.4", git = "https://github.com/foundry-rs/forge-std.git", tag = "v1.9.4" }
reactive-lib = { version = "0.0.1", git = "https://github.com/Reactive-Network/reactive-lib.git", tag = "v0.0.1" }


[rpc_endpoints]
reactive = "https://kopli-rpc.rkt.ink"

[profile.local]
eth_rpc_url = "http://127.0.0.1:8545"
reactive_rpc_url = "http://127.0.0.1:8545"

[profile.sepolia]
eth_rpc_url = "https://rpc2.sepolia.org"
reactive_rpc_url = "https://kopli-rpc.rkt.ink"

[profile.reactive]
eth_rpc_url = "https://kopli-rpc.rkt.ink"
