name: ci
on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - run: make qa
